from . import test_attendance_api
from . import test_attendance_request
from . import test_shift_api
from . import test_shift_checkin
from . import test_ot_payroll
from . import test_shift_attendance_api
from . import test_ot_credit
from . import test_shift_scope
from . import test_shift_deadline_guard
from . import test_employee_search
from . import test_request_preview
from . import test_employee_bank
from . import test_account
from . import test_department
from . import test_teaching_days

from . import test_offboarding_api
from . import test_dashboard_stats
from . import test_permissions_tpgv
from . import test_onboarding_api
from . import test_honor_board
from . import test_career
from . import test_promotion_payload
