services:
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8069:8069"
    environment:
      - HOST=${DB_HOST}
      - PORT=${DB_PORT:-5432}
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./custom-addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    command: >
      odoo
      --database=${DB_NAME:-neondb}
      --init=hocba_employees,hocba_attendance,hocba_users,hocba_recruitments
      --addons-path=/mnt/extra-addons
      --dev=xml

volumes:
  odoo_data:
