[options]
db_sslmode = require
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = ep-cool-wave-aoam4gfh-pooler.c-2.ap-southeast-1.aws.neon.tech
db_port = 5432
db_user = neondb_owner
db_password = npg_93IDXZaQneRu
