from . import hr_attendance_status
from . import hr_work_assignment
from . import hr_attendance
from . import hocba_attendance_policy
from . import hocba_attendance_office_location
from . import hocba_attendance_request
from . import hocba_work_shift
from . import hocba_shift_attendance
from . import hocba_teaching_attendance
