from . import test_policy_geofence
from . import test_policy_window
from . import test_face_distance
from . import test_checkin_flow
from . import test_status
from . import test_checkin_edge_cases
from . import test_work_credit
from . import test_check_lock
from . import test_ot_shift
from . import test_shift_attendance
from . import test_shift_deadline
from . import test_attendance_office_location
