from . import test_balances
from . import test_adjustment
from . import test_coverage
from . import test_notifications
from . import test_day_calc
from . import test_teaching_session
from . import test_leave_resolution
from . import test_teaching_conflict
from . import test_teacher_approval
from . import test_substitution
from . import test_handover_chain
from . import test_lapsed
from . import test_burnout
from . import test_approvals_domain
from . import test_attendance_integration
from . import test_work_day_lock
from . import test_work_day_unique
from . import test_work_day_import
from . import test_admin_config
