{
    'name': 'HOCBA Attendance Management',
    'version': '19.0.1.0.0',
    'category': 'Human Resources',
    'author': 'HOCBA Team',
    'license': 'LGPL-3',
    'depends': ['hr', 'web', 'hocba_employees'],
    'data': [
        'security/ir.model.access.csv',
        'data/hocba_attendance_policy_data.xml',
        'views/hr_attendance_status_views.xml',
        'views/hr_work_assignment_views.xml',
        'views/hr_attendance_views.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
    'sequence': 1,
}
